.\" Manpage for escstring.
.TH man 8 "05 Feb 2015" "1.0" "escstring man page"
.SH NAME
escstring \- escape a string on stdin
.SH SYNOPSIS
nuseradd
.SH DESCRIPTION
escstring takes input on stdin and produces a JSON-compatible string on
stdout.
.SH OPTIONS
escstring takes no options.
.SH BUGS
No known bugs.
.SH AUTHOR
Getty Ritter (getty.ritter@gmail.com)
